=== javierlago/RepasoLenguajeMarcas/1 Trimestre/Pruebas (basurero)/Trabajo_esquema (with Lucho)/Trabajo_esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Brais Dominguez Puga y Luciano Yamil Martínez Castro-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="mercadona">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ubicacion" maxOccurs="unbounded"/>
        <xs:element ref="accionistas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

<xs:element name="ubicacion">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="empleados"/>
      <xs:element ref="proveedores"/>
      <xs:element ref="clientes"/>
    </xs:sequence>
    <xs:attribute name="ciudad" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>
  
  
  <xs:element name="empleados">
   <xs:complexType>
     <xs:sequence>
       <xs:element name="director" type="xs:NMTOKENS"/>
       <xs:element name="gerente" type="xs:NMTOKENS"/>
       <xs:element name="almacenista" type="xs:NMTOKENS" maxOccurs="unbounded"/>
       <xs:element name="comercial" type="xs:NMTOKENS" maxOccurs="unbounded"/>
       <xs:element name="dependiente" type="xs:NMTOKENS" maxOccurs="unbounded"/>
       <xs:element name="limpieza" type="xs:NMTOKENS"/>
       <xs:element name="repartidor" type="xs:NMTOKENS" minOccurs="0"/>
       <xs:element name="cocinero" type="xs:NMTOKENS" minOccurs="0"/>
     </xs:sequence>
   </xs:complexType>
  </xs:element>
  
  <xs:element name="proveedores">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="empresa" maxOccurs="unbounded"/>
     </xs:sequence>
   </xs:complexType>
  </xs:element>
  
  <xs:element name="empresa">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="reparto" maxOccurs="unbounded"/>
     </xs:sequence>
     <xs:attribute name="nombre" type="xs:string" use="required"/>
   </xs:complexType>
  </xs:element>
  
  <xs:element name="reparto">
    <xs:complexType>
      <xs:attribute name="ref" type="tipoRef" use="required"/>
      <xs:attribute name="fecha" type="xs:date" use="required"/>
    </xs:complexType>
  </xs:element>
  
  
  <xs:element name="clientes">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="NIF" maxOccurs="unbounded"/>
     </xs:sequence>
   </xs:complexType>
  </xs:element>
  
  <xs:element name="NIF">
   <xs:complexType>
     <xs:sequence>
       <xs:element name="nombreCompleto"/>
       <xs:element name="telefono" type="xs:string" maxOccurs="unbounded"/>
       <xs:element name="direccion" type="xs:string" minOccurs="0"/>
       <xs:element ref="fechaNacimiento" minOccurs="0"/>
       <xs:element name="genero" type="xs:string" minOccurs="0"/>
     </xs:sequence>
     <xs:attribute name="numero" type="tipoDNI"/>
     <xs:attribute name="premium" type="tipoSiNo"/>
   </xs:complexType> 
  </xs:element>
  
  
  <xs:element name="fechaNacimiento">
      <xs:complexType>
        <xs:attribute name="dia" type="xs:short"/>
        <xs:attribute name="mes" type="xs:short"/>
        <xs:attribute name="año" type="xs:short"/>
      </xs:complexType>  
  </xs:element>
  
  <xs:element name="accionistas">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="NIFa" maxOccurs="unbounded"/>
       <xs:element ref="NIEa" maxOccurs="unbounded"/>
     </xs:sequence>
   </xs:complexType>
  </xs:element>
  
  <xs:element name="NIFa">
    <xs:complexType>
      <xs:attribute name="fechaUnión" type="xs:date"/>
      <xs:attribute name="premium" type="tipoSiNo"/>
      <xs:attribute name="num" type="tipoDNI"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="NIEa">
    <xs:complexType>
      <xs:attribute name="fechaUnión" type="xs:date"/>
      <xs:attribute name="premium" type="tipoSiNo"/>
      <xs:attribute name="num" type="tipoDNI"/>
    </xs:complexType>
  </xs:element>
  
  
  
  
  
  
  
<xs:simpleType name="tipoRef">
    <xs:restriction base="xs:string">
      <xs:pattern value="r[0-9]+"/>
    </xs:restriction>
  </xs:simpleType>

  
  <xs:simpleType name="tipoSiNo">
   <xs:restriction base="xs:string">
     <xs:pattern value="Si|No"/>
   </xs:restriction> 
  </xs:simpleType>

  <xs:simpleType name="tipoDNI">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{8}[a-z]"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== javierlago/RepasoLenguajeMarcas/1 Trimestre/Pruebas (basurero)/Trabajo_esquema (with Lucho)/Trabajo_esquemas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Brais Dominguez Puga y Luciano Yamil Martínez Castro-->
<mercadona xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Trabajo_esquema.xsd">
   <ubicacion ciudad="Vigo">
     <empleados>
       <director>Brais Dominguez</director>
       <gerente>Mario Neta</gerente>
       <almacenista>Jeff Perez</almacenista>
       <almacenista>Pepe Perez</almacenista>
       <almacenista>Manuel Gomez</almacenista>
       <comercial>Zampa Teste</comercial>
       <comercial>Carlos Jose Miguez</comercial>
       <dependiente>Henry Mendez</dependiente>
       <dependiente>Michael Jackson</dependiente>
       <dependiente>Milito Lato</dependiente>
       <limpieza>Tomás Cao</limpieza>
       <repartidor>Fernando Alonso</repartidor>
       <cocinero>Yamil Martinez</cocinero>
     </empleados>
     
     <proveedores>
       <empresa nombre="Comidas S.L.">
         <reparto ref="r45" fecha="2022-01-15"/>
         <reparto ref="r44" fecha="2022-01-14"/>
         <reparto ref="r41" fecha="2022-01-13"/>
       </empresa>
       <empresa nombre="Postres S.L.">
         <reparto ref="r56" fecha="2022-01-15"/>
         </empresa>
       <empresa nombre="Recalentados S.A.">
         <reparto ref="r66" fecha="2022-01-15"/>
       </empresa>
       <empresa nombre="Sobras Restaurantes S.C.">
         <reparto ref="r89" fecha="2022-01-16"/>
       </empresa>
       <empresa nombre="McDonals S.L.">
         <reparto ref="r99" fecha="2022-01-29"/>
       </empresa>
     </proveedores>
     
     <clientes>
       <NIF numero="12312531s" premium="Si">
         <nombreCompleto>Elsa Pato</nombreCompleto>
         <telefono>622 33 44 55</telefono>
         <telefono>642 33 74 54</telefono>
         <direccion></direccion>
         <fechaNacimiento/>
         <genero></genero>
       </NIF>
       <NIF numero="65897589m" premium="Si">
         <nombreCompleto>Ana Tomia</nombreCompleto>
         <telefono>655 55 55 50</telefono>
         <direccion>Calle Lope de Vega 129 5º</direccion>
         <fechaNacimiento dia="05" mes="12" año="1912"/>
         <genero>Hombre</genero>
       </NIF>
     </clientes>
   </ubicacion>
   
   
   <ubicacion ciudad="Nigran">
     <empleados>
       <director>Luis Vilán</director>
       <gerente>Ali Cate</gerente>
       <almacenista>Elvis Tek</almacenista>
       <almacenista>Eddy Ficio</almacenista>
       <comercial>Lola Mento</comercial>
       <dependiente>Aitor Menta</dependiente>
       <dependiente>Aitor Tilla</dependiente>
       <dependiente>Aitor Tazo</dependiente>
       <limpieza>Marc Tillo</limpieza>
     </empleados>
     
     <proveedores>
       <empresa nombre="Merienda S.L.">
         <reparto ref="r233" fecha="2022-05-22"/>
       </empresa>
     </proveedores>
     
     <clientes>
       <NIF numero="12312512s" premium="No">
         <nombreCompleto>Kiko Matamoros</nombreCompleto>
         <telefono>622 33 44 55</telefono>
         <telefono>642 93 74 50</telefono>
       </NIF>
       <NIF numero="65897889m" premium="No">
         <nombreCompleto>Andrés Tresado</nombreCompleto>
         <telefono>634 34 43 55</telefono>
         <direccion>Calle Garcia 12 5º</direccion>
         <fechaNacimiento dia="05" mes="10" año="1972"/>
         <genero>Hombre</genero>
       </NIF>
     </clientes>
   </ubicacion>
      
   <accionistas>
     <NIFa fechaUnión="2022-10-11" premium="Si" num="39493333e"/>
     <NIEa fechaUnión="2022-10-11" premium="Si" num="39493337e"/>
   </accionistas>
</mercadona>
